server:
  port: 8666
spring:
  application:
    name: springcloudrest
  redis:
      host: @redis.url@
      password: @redis.password@
      port: @redis.port@
      timeout: 30000
      jedis:
        pool:
          max-active: 20
          max-wait: 10000
          max-idle: 8
          min-idle: 0
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
feign:
  hystrix:
      enabled: true
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  #retry
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

  #Fegin
#  ribbon.ReadTimeout=60000
#  ribbon.ConnectTimeout=60000
#  ribbon.MaxAutoRetries=0
#  ribbon.MaxAutoRetriesNextServer=1