eureka:
  client:
    service-url:
          defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

server:
  port: 6666
spring:
  application:
    name: AUTHSERVICE
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      generate-unique-name: true
      druid:
        url: 'jdbc:mysql://@jdbc.url@:@jdbc.port@/user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false'
        username: @jdbc.username@
        password: @jdbc.password@
  redis:
    host: @redis.url@
    password: @redis.password@
    port: @redis.port@
    timeout: 30000
    jedis:
      pool:
        max-active: 20
        max-wait: 10000
        max-idle: 8
        min-idle: 0
hmily:
  tcc:
    serializer: kryo
    recover-delay-time: 128
    retry-max: 30
    scheduled-delay: 128
    scheduled-thread-max: 10
    repository-support: db
    tcc-db-config:
      driverClassName  : com.mysql.jdbc.Driver
      url: 'jdbc:mysql://@jdbc.url@:@jdbc.port@/user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false'
      username: @jdbc.username@
      password: @jdbc.password@
logging:
  level.org.github..*.mapper: debug